apiVersion: v1
kind: Pod
metadata:
  name: database-pod
  labels:
    name: database-pod
    app: loterry-app
spec:
  containers:
    - name: database-pod
      image: narunask/loterry-app:database
      ports:
        - containerPort: 5432