apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    name: frontend-pod
    app: loterry-app
spec:
  containers:
    - name: frontend
      image: narunask/loterry-app:frontend
      ports:
        - containerPort: 8080