apiVersion: v1
data:
  load-balancer.conf: "# Define which servers to include in the load balancing scheme.
    \n# It's best to use the servers' private IPs for better performance and security.\n#
    You can find the private IPs at your UpCloud control panel Network section.\n
    \  upstream backend {\n      server frontend-service;\n   }\n\n   # This server
    accepts all traffic to port 80 and passes it to the upstream. \n   # Notice that
    the upstream name and the proxy_pass need to match.\n\n   server {\n      listen
    80; \n\n      location / {\n          proxy_pass http://backend;\n      }\n   }\n"
kind: ConfigMap
metadata:
  creationTimestamp: "2019-12-29T04:27:26Z"
  name: confnginx-lb
  namespace: default
  resourceVersion: "17246"
  selfLink: /api/v1/namespaces/default/configmaps/confnginx-lb
  uid: 3fd1c79e-a32c-45da-a155-017f18a86288
