apiVersion: v1
kind: Service
metadata:
  name: appdb
  labels:
    name: database-service
    app: loterry-app
spec:
  selector:
    name: database-pod
    app: loterry-app
  ports:
    - port: 5432
      targetPort: 5432

