apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-pods-deployment
  labels:
    name: frontend-pods-deployment
    app: loterry_app
spec:
  template:
    metadata:
      name: frontend-pod
      labels:
        name: frontend-pod
        app: loterry-app
    spec:
      initContainers:
        - name: check-worker-ready
          image: narunask/loterry-app:worker
          command: ['sh', '-c', 'until zerorpc tcp://python:4242 ; do echo waiting for worker service to start; sleep 2; done;']
      containers:
        - name: frontend
          image: narunask/loterry-app:frontend
          ports:
            - containerPort: 8080
  replicas: 3
  selector:
    matchLabels:
      name: frontend-pod
      app: loterry-app
