apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    name: fronted-service
    app: loterry-app
spec:
  type: LoadBalancer
  selector:
    name: frontend-pod
    app: loterry-app
  ports:
    - port: 80
      targetPort: 8080