apiVersion: v1
kind: Service
metadata:
  name: lb-2-service
  labels:
    name: lb-2-service
    app: loterry-app
spec:
  selector:
    name: nginx-pod-lb-2
    app: loterry-app
  ports:
    - port: 80
      targetPort: 80
