apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-lb-deployment-2
  labels:
    name: nginx
    app: loterry-app
spec:
  template:
    metadata:
      labels:
        app: loterry-app
        name: nginx-pod-lb-2
        type: lb
    spec:
      initContainers:
        - name: check-frontend-ready
          image: curlimages/curl
          command: ['sh', '-c', 'until curl frontend-service; do echo waiting for fronted to come up; sleep 2; done;']
        - name: check-lb-1-down
          image: curlimages/curl
          command: ['sh', '-c', 'sleep 20; while curl lb-1-service; do echo waiting for nginx to go down; sleep 2; done;']
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
          - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-default-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: nginx-lb-config
              mountPath: /etc/nginx/conf.d/load-balancer.conf
              subPath: load-balancer.conf
      volumes:
        - name: nginx-config
          configMap:
            name: confnginx
        - name: nginx-lb-config
          configMap:
            name: confnginx-lb
        - name: nginx-default-config
          configMap:
            name: confnginx-default
  selector:
    matchLabels:
      app: loterry-app
  replicas: 1