apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    name: nginx
    app: loterry-app
spec:
  template:
    metadata:
      labels:
        app: loterry-app
        name: nginx-pod
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
          - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-default-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: nginx-lb-config
              mountPath: /etc/nginx/conf.d/load-balancer.conf
              subPath: load-balancer.conf
      volumes:
        - name: nginx-config
          configMap:
            name: confnginx
        - name: nginx-lb-config
          configMap:
            name: confnginx-lb
        - name: nginx-default-config
          configMap:
            name: confnginx-default
  selector:
    matchLabels:
      app: loterry-app
  replicas: 1