apiVersion: v1
kind: Pod
metadata:
  name: nginx-initial-pod
  labels:
    name: nginx-initial-pod
    app: loterry-app
    type: lb
spec:
  initContainers:
    - name: check-frontend-ready
      image: curlimages/curl
      command: ['sh', '-c', 'while curl frontend-service; do echo waiting for fronted to come up; sleep 2; done;']
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
      - containerPort: 80
      volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-default-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: nginx-lb-config
          mountPath: /etc/nginx/conf.d/load-balancer.conf
          subPath: load-balancer.conf
  volumes:
    - name: nginx-config
      configMap:
        name: confnginx
    - name: nginx-lb-config
      configMap:
        name: confnginx-lb
    - name: nginx-default-config
      configMap:
        name: confnginx-default
  restartPolicy: Never