apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    name: nginx-service
    app: loterry-app
spec:
  type: NodePort
  selector:
    type: lb
    app: loterry-app
  ports:
    - port: 80
      targetPort: 80
