apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-pods-deployment
  labels:
    name: redis-pods-deployment
    app: loterry-app
spec:
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: loterry-app
    spec:
      containers:
        - name: redis-pod
          image: narunask/loterry-app:redis
          ports:
            - containerPort: 6379
  replicas: 2
  selector:
    matchLabels:
      app: loterry-app
      name: redis-pod
