apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: loterry-app
spec:
  selector:
    name: redis-pod
    app: loterry-app
  ports:
    - port: 6379
      targetPort: 6379